services:
  auth-api:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres-auth:
        condition: service_healthy
    env_file:
      - .env.development
    ports:
      - "3001:3001"
    volumes:
      - ./auth-api:/usr/src/app  
      - /usr/src/app/node_modules
    networks:
      - backend_network
  chat-ws:
    build:
      context: ./chat-ws
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres-chat:
        condition: service_healthy
    env_file:
      - .env.development
    ports:
      - "3002:3002"
    volumes:
      - ./chat-ws:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend_network
  postgres-auth:
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    volumes:
      - postgres_auth_dev:/var/lib/postgresql/data
    networks:
      - backend_network
  postgres-chat:
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    environment:
      - DATABASE_URL=${DATABASE_URL_CHAT}
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${POSTGRES_DB_CHAT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT_CHAT}
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_CHAT}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    volumes:
      - postgres_chat_dev:/var/lib/postgresql/data
    networks:
      - backend_network
volumes:
  postgres_auth_dev:
  postgres_chat_dev:

networks:
  backend_network:
    driver: bridge