services:
  auth-api-prod:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
      target: production
    depends_on:
      postgres-auth:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - backend_network
  chat-ws-prod:
    build:
      context: ./chat-ws
      dockerfile: Dockerfile
      target: production
    depends_on:
      postgres-chat:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - backend_network
  postgres-auth:
    image: postgres:16
    restart: always
    env_file:
      - .env.production
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    volumes:
      - postgres_auth_prod:/var/lib/postgresql/data
    networks:
      - backend_network
  postgres-chat:
    image: postgres:16
    restart: always
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=${DATABASE_URL_CHAT}
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${POSTGRES_DB_CHAT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT_CHAT}
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_CHAT}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    volumes:
      - postgres_chat_prod:/var/lib/postgresql/data
    networks:
      - backend_network
  redis-cache:
    image: redis:latest
    restart: always
    env_file:
      - .env.development
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1m30s
      timeout: 30s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - backend_network
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - auth-api-prod
      - chat-ws-prod
    networks:
      - backend_network

volumes:
  postgres_auth_prod:
  postgres_chat_prod:

networks:
  backend_network:
    driver: bridge