services:
  auth-api-dev:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres-dev:
        condition: service_healthy
    env_file:
      - .env.development
    ports:
      - "3001:3001"
    networks:
      - backend_network
  chat-ws:
    build:
      context: ./chat-ws
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.development
    ports:
      - "3002:3002"
    networks:
      - backend_network
  postgres-dev:
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emilio_botier_dev -d auth_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - backend_network
volumes:
  postgres_data_dev:

networks:
  backend_network:
    driver: bridge