services:
  auth-api:
    build:
      context: ./auth-api
      target: development
    ports:
      - 3001:3001
    env_file:
      - ./auth-api/.env.development
    volumes:
        - ./auth-api:/usr/src/app
        - node_modules_auth:/usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
  postgres:
    image: postgres:16
    container_name: auth_postgres_db_dev
    restart: always
    env_file:
      - ./auth-api/.env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emilio_botier -d auth_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  postgres_data:
  node_modules_auth:

networks:
  backend:
    driver: bridge