services:
  auth-api-dev:
    build: 
      context: ./auth-api
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres-dev:
        condition: service_healthy
    env_file:
      - .env.development
    ports:
      - "3001:3001"
    networks:
      - backend_network
  chat-ws:
    build:
      context: ./chat-ws
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.development
    ports:
      - "3002:3002"
    networks:
      - backend_network
  postgres-dev:
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emilio_botier_dev -d auth_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - backend_network
  postgres-chat-dev:
    image: postgres:16
    restart: always
    env_file:
      - .env.development
    environment:
      - DATABASE_URL=${DATABASE_URL_CHAT}
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${POSTGRES_DB_CHAT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT_CHAT}
    ports: 
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_CHAT}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_chat_dev:/var/lib/postgresql/data
    networks:
      - backend_network
volumes:
  postgres_data_dev:
  postgres_chat_dev:

networks:
  backend_network:
    driver: bridge